2022-03-28 13:46:57,159 [my_agent_code] INFO: Loading model from saved state.
2022-03-28 13:46:58,558 [my_agent_wrapper] ERROR: CUDA error: out of memory
Traceback (most recent call last):
  File "/home/jia/bomberman_rl/agents.py", line 248, in process_event
    event_result = getattr(module, event_name)(self.fake_self, *event_args)
  File "/home/jia/bomberman_rl/agent_code/my_agent/callbacks.py", line 37, in setup
    self.model = pickle.load(file)
  File "/home/jia/anaconda3/lib/python3.8/site-packages/torch/storage.py", line 141, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/home/jia/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/jia/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 774, in _legacy_load
    result = unpickler.load()
  File "/home/jia/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 730, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/jia/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/jia/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 155, in _cuda_deserialize
    return storage_type(obj.size())
  File "/home/jia/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 462, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory
